export const authenticationConstants = {
    AUTHENTICATION_REQUEST: 'AUTHENTICATION_REQUEST',
    AUTHENTICATION_REQUEST_SUCCESS: 'AUTHENTICATION_REQUEST_SUCCESS',
    AUTHENTICATION_REQUEST_FAILURE: 'AUTHENTICATION_REQUEST_FAILURE',
    AUTHENTICATION_LOGOUT_SUCCESS: 'AUTHENTICATION_LOGOUT_SUCCESS',
    INCREASE_LOANS_COUNTER: 'INCREASE_LOANS_COUNTER',
    DECREASE_LOANS_COUNTER: 'DECREASE_LOANS_COUNTER',
};