export const cartConstants = {
    ADD: 'ADD_TO_CART',
    REMOVE: 'REMOVE_FROM_CAR',
    SUCCESS: 'CART_REQUEST_SUCCESS',
    ERROR: 'CART_REQUEST_ERROR',
    REQUEST: 'CART_REQUEST_START',
    CLEAR: 'CLEAR_CART',
    CHECKOUT: 'CART_CHECKOUT'
};