export const categoryConstants = {
    SET_CATEGORIES: 'SET_CATEGORIES',
    REQUEST_CATEGORY_ACTION: 'REQUEST_CATEGORY_ACTION',
    SUCCESS_CATEGORY_ACTION: 'SUCCESS_CATEGORY_ACTION',
    FAILED_CATEGORY_ACTION: 'FAILED_CATEGORY_ACTION'
};