export const filterConstants = {
    FILTER_CLASSIFICATION: 'FILTER_CLASSIFICATION',
    FILTER_CATEGORY: 'FILTER_CATEGORY',
    FILTER_SORT: 'FILTER_SORT',
    SET_FILTER: 'SET_FILTER',
    SET_SORT: 'SET_SORT',
    CLEAR: 'CLEAR',
    SET_PAGINATION: 'SET_PAGINATION'
};