export const movieConstants = {
    SET_MOVIES: 'SET_MOVIES',
    SELECT_MOVIE: 'SELECT_MOVIE',
    ADD_MOVIE: 'ADD_MOVIE',
    UPDATE_MOVIE: 'UPDATE_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    REQUEST_MOVIE_ACTION: 'REQUEST_MOVIE_ACTION',
    SUCCESS_MOVIE_ACTION: 'SUCCESS_MOVIE_ACTION',
    FAILED_MOVIE_ACTION: 'FAILED_MOVIE_ACTION'
};